name: Test

on: [push]

jobs:
  test:
    env:
      RAILS_ENV: test
      NODE_ENV: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Prepare DB
        run: |
          cp config/database.github.yml config/database.yml
      bundle exec rails db:test:prepare
      - name: Run system tests # Minitest
        run: bundle exec rails test:system
      - name: Run unit tests # Minitest
        run: bundle exec rails test:models
      - name: Run RSpec tests #RSpec
        run: bundle exec rspec spec/models
