name: Test

on: [push]

jobs:
  test:
    env:
      RAILS_ENV: test
      NODE_ENV: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run system tests # Minitest
        run: bundle exec rails test:system
      - name: Run unit tests # Minitest
        run: rbundle exec rails test:models
      - name: Run RSpec tests
        run: rspec spec/models
